### ISSUE TITLE
Feature request: commands in menus

### ISSUE THREAD

**Issue by jacobweber** [egodigital/vscode-powertools#10]
Would it be possible to let us configure certain commands to be available in file-explorer context menus?

I'm not sure whether vscode allows extensions to add context-menu commands dynamically. But if so, this would allow us to write commands that work on directories, not just files, and make it easier to run them.

**Comment by ghost** [comment]
@jacobweber 

I think, that it is possible ... maybe as general context menu entry like `Execute command ...`, which lists and executes all commands, which are marked as commands for things like the file explorer.

Maybe in the next release, we should be able to implement that feature.

**Comment by ghost** [comment]
@jacobweber 

**Feature has been implemented since version 0.19.2** (you need to have [Visual Studio Code 1.31](https://code.visualstudio.com/updates/v1_31) being installed).

You can now set `forFile` and/or `forFolder` to `(true)`, which make commands available in:

* command palette (for active editor)
* context menu (of underlying editor)
* file explorer

For more information, s. [File explorer and context menus](https://github.com/egodigital/vscode-powertools/wiki/Commands#file-explorer-and-context-menus).

**Comment by jacobweber** [comment]
Geez, what took you so long? 😀

**Comment by jacobweber** [comment]
Uh oh, found a bug. When I use the context menu in the Explorer, it shows me the appropriate commands, but then it executes the chosen command based on the open editor, not the selected file.

**Comment by jacobweber** [comment]
(ignore deleted comment -- I was using args incorrectly.)

**Comment by jacobweber** [comment]
(ignore deleted comment -- I was using args incorrectly.)
