### ISSUE TITLE
How to use current file extension in an if-clause?

### ISSUE THREAD

**Issue by mbaas2** [egodigital/vscode-powertools#13]
I have set up a button to launch a shell-cmd on the current file. Works fine.
Now I wanted to only show that button if the file is of appropriate type.

Googled the following test and tried it i a debug-console:
`(/(dyalog|mipage)$/ig.test(activeFile.substr((activeFile.lastIndexOf('.') +1))))`

But this assumed we had a `var activeFile` which we don't. So I tried to code around that and ended up with the following - but it doesn't seem to work (does not show the icon for .dyalog-files):
`"if": '(/(dyalog|mipage)$/ig.test("${activeFile}".substr(("${activeFile}".lastIndexOf(".") +1))))',`

Can't I use ${activeFile} in `if´s or is there another mistake?

**Comment by ghost** [comment]
@mbaas2 

You have to use `$v` constant, where `activeFile` should be stored (s. [global values](https://github.com/egodigital/vscode-powertools/wiki/Values#global-values)):

```
(/(dyalog|mipage)$/ig.test( $v['activeFile'].substr(( $v['activeFile'].lastIndexOf('.') +1)) ))
```

**Comment by mbaas2** [comment]
Thanks for the quick reply! 
Unfortunately that did not work. So I added another button to diagnose the problem:
```
              {
                "text": "Datei:${activeFile}",
              }
```
And I noticed when I changed file, this button's text didn't change. So I understand why my original btn does not show. Shouldn't `activeFile `be updated if I activate another file?

**Comment by mbaas2** [comment]
Actually...thinking about if - wouldn't it be cool if the button could have a parameter like `filterFileRegex` (and only if the rx matched the filename btn would be shown) ?

**Comment by ghost** [comment]
@mbaas2

The problem is, that the button is rendered once, the time the configuration has been updated.

So, the values are read and rendered also once.

There is currently no automatic update event.

But this is a good feature for the next release (what will be in about 2 days).

Yes, `filterFileRegex` is also a very good idea for a new setting :-)

**Comment by mbaas2** [comment]
Cool, thanks - only 2 days to wait! (Hope I can sleep!) ;-)

**Comment by ghost** [comment]
I hope so! :D

**Comment by mbaas2** [comment]
I'll try me best ;-)

**Comment by ghost** [comment]
@mbaas2 

**Since version 0.36.0**, there are two new features for [buttons](https://github.com/egodigital/vscode-powertools/wiki/Buttons) and [command buttons](https://github.com/egodigital/vscode-powertools/wiki/Commands#button):

**[onEditorChanged](https://github.com/egodigital/vscode-powertools/wiki/Executable%20Settings#oneditorchanged):**

A (JavaScript) code to executed after active editor has changed:

```javascript
{
    "ego.power-tools": {
        "buttons": [
            {
                "text": "Button: ${activeFile}",
                "action": {
                    "type": "script",
                    "script": "mybutton.js"
                },

                "onEditorChanged": " $v['button'].update() "
            }
        ]
    }
}
```

**ifFile:**

A regular expression, that checks if that button should be visible for an active editor or not.

```javascript
{
    "ego.power-tools": {
        "buttons": [
            {
                "text": "Button: ${activeFile}",
                "action": {
                    "type": "script",
                    "script": "mybutton.js"
                },

                "ifFile": "(test\\.txt)$"
            }
        ]
    }
}
```

**Comment by mbaas2** [comment]
Super - works exactly as I had hoped! :-)  Thanks very much for the speedy implementation!
