### ISSUE TITLE
Feature request: Allow --inspect command.

### ISSUE THREAD

**Issue by Ragnoroct** [egodigital/vscode-powertools#21]
It would be pretty awesome if there was a configuration setting you could set `--inspect` as a nodejs argument so you can debug your powertool scripts

**Comment by ghost** [comment]
@Ragnoroct 

Currently I only know the following solution:

First open your project, where your Power Tool scripts are used and running (`Project Window`).

Then open a new window (`Debug Window`) in an empty folder, which should only be used for debugging other Node.js processes.

Create a `.vscode/launch.json` file with the following content in the workspace of the `Debug Window`:

```jsonc
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "attach",
            "name": "Attach by Process ID",
            "processId": "${command:PickProcess}"
        }
    ]
}
```

Open the script(s) of the `Project Window` in the `Debug Window` and set a breakpoint there.

Then start the debug configuration `Attach by Process ID` in the `Debug Window` and select the process of the `Project Window`.

Now, when you run a script, the debugger in the `Debug Window` should now stop at the breakpoint.

You cannot do this in the same window, because the debugger instance in `Project Window` would freeze.

**But I think that this will be a very good new feature for the next release, because the API of VSCode can start a debug configuration by an extension, using [startDebugging()](https://code.visualstudio.com/api/references/vscode-api#debug) function.**

**Comment by ghost** [comment]
@Ragnoroct 

That version of the extension is no longer supported.

Please backup, uninstall and upgrade to the [new location](https://marketplace.visualstudio.com/items?itemName=egomobile.vscode-powertools).
