### ISSUE TITLE
executeCommand("cmake.buildDirectory") gives: Cannot read property 'uri' of undefined

### ISSUE THREAD

**Issue by giantmustache** [egodigital/vscode-powertools#35]
I am using vscode powertools to write a little script that enhances the `ms-vscode.cmake-tools` plugin. It used to work a month or two ago when I used it, but something changed in my setup (vs code version/powertools version/cmake tools version) that make my script say `Cannot read property 'uri' of undefined`.

I have narrowed the example down to the following script:

```ts
// relativeTargetPath.js
exports.execute = async (args) => {
    const vscode = args.require('vscode');
    return vscode.commands.executeCommand('cmake.buildDirectory');
};
```

```json
// in my workspace settings
"ego.power-tools": {
    "commands": {
        "relativeTargetPath": {
            "script": "relativeTargetPath.js"
        }
    }
```

The odd thing is that the command `cmake.buildDirectory` works in a task:

```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "echo",
      "type": "shell",
      "command": "echo ${cmake.buildDirectory}"
    }
  ]
}
```

Is this something that could be going wrong in powertools or is it cmake tools or just vs code?

Info:
vs code 1.43.2
ms-vscode.cmake-tools 1.3.1
ego-digital.vscode-powertools 0.58.0

**Comment by ghost** [comment]
@giantmustache 

I have tested it, and it works for me.

In my case, the command returns `(null)`, because I did not setup anything.

I have looked [at the source code](https://github.com/microsoft/vscode-cmake-tools/blob/553ea368ccfa39139a1dbabd0130a8e247f73087/src/cmake-tools.ts#L1091) and nothing seems to be different.

Where is your script file (`relativeTargetPath.js`) stored, `.vscode` sub folder?

Since what time do you have that configuration?

**Comment by giantmustache** [comment]
This script was definitely working 3 or 4 months ago. The script is indeed in the .vscode sub folder.
So you think that the error is within the cmake tools itself? Strange that it is different when running it via "${cmake.buildDirectory}" then.

**Comment by giantmustache** [comment]
I reverted cmake tools to 1.2.3 and it all works fine. Going to write a cmake tools github issue instead.
