### ISSUE TITLE
Is there a value/placeholder for current active file path?

### ISSUE THREAD

**Issue by zhaocai** [egodigital/vscode-powertools#5]
For Example, how can I make a button to open current editing file in notepad.exe?

```json
{
    "ego.power-tools": {
        "buttons": [
            {
                "text": "open in notepad'",
                "action": {
                    "type": "shell",
                    "command": "/path/to/notepad.exe ${activeFile}"
                }
            }
        ]
    }
}```

**Comment by ghost** [comment]
@zhaocai 

Since version 0.9.0 there is a new global [value](https://github.com/egodigital/vscode-powertools/wiki/Values#global-values) called `activeFile`.

You should also set the new `wait` property to `(false)`, otherwise it can happen that the command will always show the notification window at the right bottom corner:

```json
{
    "ego.power-tools": {
        "buttons": [
            {
                "text": "open in notepad'",
                "action": {
                    "type": "shell",
                    "command": "\"/path/to/notepad.exe\" \"${activeFile}\"",
                    "wait": false
                }
            }
        ]
    }
}
```

**Comment by zhaocai** [comment]
@mkloubertego thanks for the update. Can I use this `shell` type as a command?

**Comment by zhaocai** [comment]
One more thing, duplicate buttons are generated for workspace with multiple folders. Is this intended?

**Comment by ghost** [comment]
@zhaocai 

Yes, because settings are inherited.

As workarround, you can use the new [onCreated and onDestroyed](https://github.com/egodigital/vscode-powertools/wiki/Executable%20Settings#oncreated-and-ondestroyed) settings, combined with [if](https://github.com/egodigital/vscode-powertools/wiki/Conditional%20Settings):

```json
{
    "ego.power-tools": {
        "buttons": [
            {
                "text": "open in notepad'",
                "action": {
                    "type": "shell",
                    "command": "\"/path/to/notepad.exe\" \"${activeFile}\"",
                    "wait": false
                },

                "if": " !$s['openInNotepadButton'] ",
                "onCreated": " $s['openInNotepadButton'] = true ",
                "onDestroyed": " delete $s['openInNotepadButton'] "
            }
        ]
    }
}
```

What happens:

The very first button, will write to the [session storage](https://github.com/egodigital/vscode-powertools/wiki/Executable%20Settings#s) and mark itself as being created as [button](https://github.com/egodigital/vscode-powertools/wiki/Buttons) of the `openInNotepadButton` "category" (s. `onCreated`).

The next button will check via `if`, if there was already a button, that has been created for that category. If so, it will not be created.

After an existing button has been destroyed, it will unmark itself (s. `onDestroyed`).

We are currently working on a smarter solution, which will make it possible to register things, like buttons or [jobs](https://github.com/egodigital/vscode-powertools/wiki/Jobs) globally and/or define things like an ID.

**Comment by ghost** [comment]
@zhaocai 

**Version 0.12.0 now supports [global settings](https://github.com/egodigital/vscode-powertools/wiki/Global-Settings).**

In [that issue post](https://github.com/egodigital/vscode-powertools/issues/4#issuecomment-456993336) I describe how to use them.
